### ISSUE TITLE
Python的requests库无法读取csv数据

### ISSUE THREAD

**Issue by YuudachiYuudachiPoi** [v2fly/v2ray-core#1104]
## 你正在使用哪个版本的 V2Ray？

4.40.1(来自[kuoruan](https://github.com/kuoruan/luci-app-v2ray)的openwrt版本)

## 你的使用场景是什么？

使用电脑连接到路由器的socks代理，直接全部direct。(平时不是这样设置的，但这样设置问题依然存在）

## 你看到的异常现象是什么？

在运行运行下方python代码时,会返回SSLError

```
import requests
home_data = requests.get(url='https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv')
```

下面是Error信息
```
Traceback (most recent call last):
  File "path", line 32, in <module>
    home_data = requests.get(url='https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv')      
  File "C:\Users\mcgog\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\mcgog\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mcgog\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mcgog\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mcgog\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

## 你期待看到的正常表现是怎样的？

正常读取数据

## 请附上你的配置

**客户端配置：**

```javascript
{
	"log": {
		"access": "/var/log/v2ray-access.log",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"network": "tcp,udp",
				"outboundTag": "direct"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 10808,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "192.168.1.1"
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},
		{
			"listen": "0.0.0.0",
			"port": 10809,
			"protocol": "http",
			"settings": {
				"allowTransparent": false
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"tag": "direct"
		}
	]
}
```

## 请附上出错时软件输出的错误日志

**客户端错误日志：**

```javascript
2021/07/01 20:12:49 [Warning] V2Ray 4.40.1 started
2021/07/01 20:12:57 [Warning] [3443634219] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > malformed HTTP request "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03tc\xdf\xf0\xb3Mf[\xb1s\xa8\xfe\xb1\xb0uG\xfbS\xb7YT^\x8e\xe5\x84e\x8b\xe9\x1fm\x8b\x83 \xf9`\x9cv\xf3ë\x1f!\x1c\xe6B\xd8P\xc9,\x04\xf8=܇\vu\xec\xf8\xc8\xffާ\x04\x19\xef\x00V\x13\x02\x13\x03\x13\x01\xc0,\xc00\xc0+\xc0/̨̩\x00\x9f\x00\x9e̪\xc0\xaf\xc0\xad\xc0\xae\xc0\xac\xc0$\xc0(\xc0#\xc0'\xc0"
```

**Comment by kslr** [comment]
socks vs http ?

**Comment by YuudachiYuudachiPoi** [comment]
我两个都试过了，都是一样的问题
![image](https://user-images.githubusercontent.com/35692076/124220262-981a2a80-dacb-11eb-9925-e525f8ba1f14.png)
![image](https://user-images.githubusercontent.com/35692076/124220303-aa946400-dacb-11eb-9677-cb50318f1ba2.png)

**Comment by kslr** [comment]
https://stackoverflow.com/questions/65931275/python-requests-module-does-it-use-system-level-on-windows-proxy-settings

**Comment by YuudachiYuudachiPoi** [comment]
我看看python的proxy设置吧，如果python没有应用系统proxy的话，那为什么开了系统proxy就出问题了。我试出来再说吧，也有可能不是v2ray的问题。

**Comment by YuudachiYuudachiPoi** [comment]
的确是系统proxy或者python读取proxy的问题，我用Proxifier就没有这个问题了。谢谢
