### ISSUE TITLE
启动时fatal错误退出: out of memory

### ISSUE THREAD

**Issue by happier233** [v2fly/v2ray-core#1206]
## 你正在使用哪个版本的 V2Ray？

4.41.1

## 你的使用场景是什么？

服务器启动

## 你看到的异常现象是什么？

启动失败，严重错误退出。在4.40.1正常，升级后严重错误，退回后正常。

## 请附上你的配置

**服务端配置：**

```javascript
```

**客户端配置：**

```javascript

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf25ff8, 0x16)
        runtime/panic.go:1117 +0x72
runtime.sysMap(0xc014000000, 0x4000000, 0x16129b0)
        runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x15f8260, 0x400000, 0x42c257, 0x15f8268)
        runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x15f8260, 0x1e, 0x0)
        runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x15f8260, 0x1e, 0x0, 0x1fe)
        runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:910 +0x59
runtime.systemstack(0x46d221)
        runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:339 fp=0xc006130d38 sp=0xc006130d30 pc=0x46b520
runtime.(*mheap).alloc(0x15f8260, 0x1e, 0x5f0100, 0xc00544c65d)
        runtime/mheap.go:904 +0x85 fp=0xc006130d88 sp=0xc006130d38 pc=0x427f05
runtime.(*mcache).allocLarge(0x7f7df6cb4108, 0x3c000, 0x4d0001, 0x0)
        runtime/mcache.go:224 +0x97 fp=0xc006130de0 sp=0xc006130d88 pc=0x418577
runtime.mallocgc(0x3c000, 0xf08180, 0x4da401, 0xe71f60)
        runtime/malloc.go:1078 +0x925 fp=0xc006130e68 sp=0xc006130de0 pc=0x40dfc5
runtime.growslice(0xf08180, 0xc013f80000, 0x6000, 0x6000, 0x6001, 0xc000000000, 0x0, 0x1051428)
        runtime/slice.go:230 +0x1e9 fp=0xc006130ed0 sp=0xc006130e68 pc=0x44ede9
google.golang.org/protobuf/internal/impl.pointer.AppendPointerSlice(...)
        google.golang.org/protobuf@v1.27.1/internal/impl/pointer_unsafe.go:132
google.golang.org/protobuf/internal/impl.consumeMessageSliceInfo(0xc00544c649, 0x7865, 0xc9dda0, 0xc013af85d8, 0xc006130f02, 0xc0003f88a8, 0xea7f00, 0x1051428, 0xc000030330, 0x15, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go:507 +0x27a fp=0xc006130f80 sp=0xc006130ed0 pc=0x5bb35a
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc000109010, 0xc00544c649, 0x6c75c, 0xc9dda0, 0xc013af85a0, 0xc000000000, 0x6c700, 0x1051428, 0xc000030330, 0x2e2b, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/decode.go:139 +0x54a fp=0xc0061310b0 sp=0xc006130f80 pc=0x5f11ca
google.golang.org/protobuf/internal/impl.consumeMessageSliceInfo(0xc0053e774f, 0xd02c9a, 0xd02c9a, 0xc00017f3a8, 0x1069202, 0xc000454120, 0xc000109000, 0x1051428, 0xc000030330, 0x2e2d, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go:503 +0x193 fp=0xc006131160 sp=0xc0061310b0 pc=0x5bb273
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc000109158, 0xc0053e774f, 0x2eea3e9, 0xd02c9a, 0xc00017f380, 0x0, 0x1069200, 0x1051428, 0xc000030330, 0x0, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/decode.go:139 +0x54a fp=0xc006131290 sp=0xc006131160 pc=0x5f11ca
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal(0xc000109158, 0x1066fe8, 0xc00017f380, 0xc003200000, 0x2eea3e9, 0x2eea3e9, 0x0, 0x1051428, 0xc000030330, 0x608f7d, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/decode.go:62 +0xbb fp=0xc006131308 sp=0xc006131290 pc=0x5f0bfb
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal-fm(0x1066fe8, 0xc00017f380, 0xc003200000, 0x2eea3e9, 0x2eea3e9, 0x0, 0x1051428, 0xc000030330, 0x4b2873, 0x4668f4, ...)
        google.golang.org/protobuf@v1.27.1/internal/impl/decode.go:55 +0x68 fp=0xc006131378 sp=0xc006131308 pc=0x6167e8
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal(0x101, 0x1051428, 0xc000030330, 0xc003200000, 0x2eea3e9, 0x2eea3e9, 0x1066fe8, 0xc00017f380, 0xe7bf20, 0x1, ...)
        google.golang.org/protobuf@v1.27.1/proto/decode.go:93 +0x295 fp=0xc006131428 sp=0xc006131378 pc=0x54bcb5
google.golang.org/protobuf/proto.Unmarshal(0xc003200000, 0x2eea3e9, 0x2eea3e9, 0x1047640, 0xc00017f380, 0x0, 0x0)
        google.golang.org/protobuf@v1.27.1/proto/decode.go:50 +0x85 fp=0xc006131490 sp=0xc006131428 pc=0x54b865
github.com/v2fly/v2ray-core/v4/infra/conf/geodata/standard.loadIP(0xf1b899, 0x9, 0xc0004072d6, 0x7, 0x0, 0xc000170342, 0x40a51f, 0xc00040c000, 0xde8900)
        github.com/v2fly/v2ray-core/v4/infra/conf/geodata/standard/standard.go:21 +0x265 fp=0xc006131548 sp=0xc006131490 pc=0xc380e5
github.com/v2fly/v2ray-core/v4/infra/conf/geodata/standard.standardLoader.LoadIP(...)
        github.com/v2fly/v2ray-core/v4/infra/conf/geodata/standard/standard.go:60
github.com/v2fly/v2ray-core/v4/infra/conf/geodata/standard.(*standardLoader).LoadIP(0x160f018, 0xf1b899, 0x9, 0xc0004072d6, 0x7, 0x40b9c5, 0xde8900, 0xdbc080, 0x1069200, 0x1047fc0)
        <autogenerated>:1 +0x65 fp=0xc0061315a0 sp=0xc006131548 pc=0xc38ba5
github.com/v2fly/v2ray-core/v4/infra/conf/geodata.(*loader).LoadGeoIP(0xc000289f20, 0xc0004072d6, 0x7, 0x1047f00, 0xc000289f10, 0x2, 0x2, 0xc0003df660)
        github.com/v2fly/v2ray-core/v4/infra/conf/geodata/geodata.go:58 +0x62 fp=0xc006131600 sp=0xc0061315a0 pc=0xc34122
github.com/v2fly/v2ray-core/v4/infra/conf/rule.toCidrList(0x105b300, 0xc00044e450, 0xc00017fe40, 0x1, 0x4, 0x0, 0x0, 0x2, 0x0, 0xa8)
        github.com/v2fly/v2ray-core/v4/infra/conf/rule/rule.go:130 +0x237 fp=0xc0061317a8 sp=0xc006131600 pc=0xccca37
github.com/v2fly/v2ray-core/v4/infra/conf/rule.parseFieldRule(0x105b300, 0xc00044e450, 0xc0001702c0, 0xa8, 0xb0, 0x0, 0x0, 0xe3a520)
        github.com/v2fly/v2ray-core/v4/infra/conf/rule/rule.go:263 +0x825 fp=0xc0061318e8 sp=0xc0061317a8 pc=0xcce545
github.com/v2fly/v2ray-core/v4/infra/conf/rule.ParseRule(0x105b300, 0xc00044e450, 0xc0001702c0, 0xa8, 0xb0, 0x0, 0x8, 0xc00044e450)
        github.com/v2fly/v2ray-core/v4/infra/conf/rule/rule.go:322 +0x20b fp=0xc006131970 sp=0xc0061318e8 pc=0xccf06b
github.com/v2fly/v2ray-core/v4/infra/conf.(*RouterConfig).Build(0xc000072aa0, 0xc000067268, 0x3, 0xc0002df4e8)
        github.com/v2fly/v2ray-core/v4/infra/conf/router.go:112 +0x478 fp=0xc006131a38 sp=0xc006131970 pc=0xcdcbb8
github.com/v2fly/v2ray-core/v4/infra/conf.(*Config).Build(0xc0001901c0, 0xc00016dbf0, 0xc0001902a0, 0x0)
        github.com/v2fly/v2ray-core/v4/infra/conf/v2ray.go:537 +0x1dd1 fp=0xc006131d20 sp=0xc006131a38 pc=0xcec651
github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1(0xda0b20, 0xc00000df38, 0x7ffed086c806, 0x4, 0xc000106160)
        github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:36 +0xaf fp=0xc006131db0 sp=0xc006131d20 pc=0xcf40ef
github.com/v2fly/v2ray-core/v4.LoadConfig(0xf16edc, 0x4, 0x7ffed086c7ea, 0x20, 0xda0b20, 0xc00000df38, 0x104a560, 0xc00000e020, 0xc0003dfe88)
        github.com/v2fly/v2ray-core/v4/config.go:67 +0x268 fp=0xc006131e00 sp=0xc006131db0 pc=0x891b88
main.startV2Ray(0xc0000682a0, 0xc0000300a0, 0x2, 0x2)
        github.com/v2fly/v2ray-core/v4/main/main.go:110 +0x12e fp=0xc006131ea8 sp=0xc006131e00 pc=0xcf670e
main.main()
        github.com/v2fly/v2ray-core/v4/main/main.go:139 +0xb1 fp=0xc006131f88 sp=0xc006131ea8 pc=0xcf6c31
runtime.main()
        runtime/proc.go:225 +0x256 fp=0xc006131fe0 sp=0xc006131f88 pc=0x439676
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc006131fe8 sp=0xc006131fe0 pc=0x46d221

goroutine 6 [select]:
github.com/v2fly/v2ray-core/v4/common/log.(*generalLogger).run(0xc000066080)
        github.com/v2fly/v2ray-core/v4/common/log/logger.go:54 +0x192
created by github.com/v2fly/v2ray-core/v4/common/log.(*generalLogger).Handle
        github.com/v2fly/v2ray-core/v4/common/log/logger.go:77 +0xa9
```

**Comment by happier233** [comment]
又测试了一下，4.41.0也是正常的，尝试加了--test，直接就提示Killed，退回到4.41.0是Configuration OK.

**Comment by Loyalsoldier** [comment]
下载使用最新的 geoip.dat 即可
