### ISSUE TITLE
V5 LeastLoadStrategy panic

### ISSUE THREAD

**Issue by cyber9723470** [v2fly/v2ray-core#1529]
## What version of V2Ray are you using?

v5.0.2 Developer Preview 

## What problems have you encountered?
LeastLoadStrategy panic

## Please attach your configuration here
```
"routing": {
        "balancers": [
            {
                "tag": "servers",
                "selector": [
                    "servers"
                ],
                "strategy": {
                    "type": "LeastLoad",
                    "settings": {
                        "healthCheck": {
                            "destination": "http://detectportal.firefox.com/success.txt",
                            "connectivity": "http://connectivitycheck.platform.hicloud.com/generate_204",
                            "timeout": 5,
                            "interval": 60,
                            "sampling": 10
                        },
                        "maxRTT": "500s",
                        "expected": 1,
                        "baselines": [
                            "30s",
                            "50s",
                            "100s",
                            "200s"
                        ]
                    }
                }
            },
```

## Please attach error logs here

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x10d4858]

goroutine 110 [running]:
github.com/v2fly/v2ray-core/v5/app/router.(*LeastLoadStrategy).getNodes(0xc008002600, {0xc008a0e160, 0x0, 0x1}, 0x746a528800)
        github.com/v2fly/v2ray-core/v5/app/router/strategy_leastload.go:149 +0xf8
github.com/v2fly/v2ray-core/v5/app/router.(*LeastLoadStrategy).pickOutbounds(0xc008002600, {0xc008a0e160, 0x0, 0x10cd2a0})
        github.com/v2fly/v2ray-core/v5/app/router/strategy_leastload.go:78 +0x2a
github.com/v2fly/v2ray-core/v5/app/router.(*LeastLoadStrategy).PickOutbound(0xc0004c3c00, {0xc008a0e160, 0x18, 0x18})
        github.com/v2fly/v2ray-core/v5/app/router/strategy_leastload.go:68 +0x25
github.com/v2fly/v2ray-core/v5/app/router.(*Balancer).PickOutbound(0xc0004c3c00)
        github.com/v2fly/v2ray-core/v5/app/router/balancing.go:44 +0x1f4
github.com/v2fly/v2ray-core/v5/app/router.(*Rule).GetTag(...)
        github.com/v2fly/v2ray-core/v5/app/router/config.go:28
github.com/v2fly/v2ray-core/v5/app/router.(*Router).PickRoute(0x1757720, {0x176fbb0, 0xc0072f2510})
        github.com/v2fly/v2ray-core/v5/app/router/router.go:80 +0x5a
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc007f3db40, {0x1757720, 0xc0005e35f0}, 0xc0000711c0, {{0x1758a28, 0xc0073182a0}, 0x0, 0x0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:300 +0xdf
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:215 +0x465
```

**Comment by AkinoKaede** [comment]
It looks like the configuration is incorrect.

https://github.com/v2fly/v2ray-core/blob/3ef7feaeaf737d05c5a624c580633b7ce0f0f1be/infra/conf/v4/observatory.go#L28-L32

**Comment by cyber9723470** [comment]
After adding selectors into `observatory` as `subjectSelector`, the configuration seems to work.
Would it be nice if the observatory can be automatically created when a LeastLoad balancer is present?

**Comment by cyber9723470** [comment]
Now I am confused. If I use `burstObservatory` instead of `observatory` in the v2 json configuration, it crashes with the same error. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xe9740f]
```

**Comment by cyber9723470** [comment]
After adding selectors into `observatory` as `subjectSelector`, the v2ray does not crash anymore, but the balancer is still not working. All traffic is routed into the default even if I use
```   {
                "type": "field",
                "inboundTag": [
                    "socks"
                ],
                "balancerTag": "servers"
            }
```
