### ISSUE TITLE
Debian/Unstable 的 v2ray 包报 panic: crypto/hmac

### ISSUE THREAD

**Issue by sommio** [v2fly/v2ray-core#1730]
## 你正在使用哪个版本的 V2Ray？

4.34.0-5 (Debian/Unstable)

## 你的使用场景是什么？

服务端

## 你看到的异常现象是什么？

运行 v2ray 会报错 panic: crypto/hmac: hash generation function does not produce unique values

## 你期待看到的正常表现是怎样的？

正常运行 v2ray

## 请附上你的配置

**服务端配置：**

```javascript
{
  "inbounds": [
    {
      "port": 3334,
      "protocol": "vmess",
      "settings":{
        "clients":[
          {
          "id": "3e3343e2-13d8-44c3-887f-46675e7bf313"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

## 请附上出错时软件输出的错误日志

** v2ray --test --config /etc/v2ray/config.json **

```javascript
V2Ray 4.34.0 (user) 20220118-150717 (go1.17.6 linux/amd64)
A unified platform for anti-censorship.
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc00015b5f0, {0xc000038a80, 0x16, 0x18})
	crypto/hmac/hmac.go:143 +0x292
v2ray.com/core/proxy/vmess/aead.KDF({0xc000171c20, 0x10, 0x10}, {0xc00015b640, 0x1, 0x10})
	v2ray.com/core/proxy/vmess/aead/kdf.go:13 +0x127
v2ray.com/core/proxy/vmess/aead.KDF16(...)
	v2ray.com/core/proxy/vmess/aead/kdf.go:22
v2ray.com/core/proxy/vmess/aead.NewCipherFromKey({0xc000171c20, 0x618573, 0xc0000d4180})
	v2ray.com/core/proxy/vmess/aead/authid.go:41 +0x4a
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoder(...)
	v2ray.com/core/proxy/vmess/aead/authid.go:53
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
	v2ray.com/core/proxy/vmess/aead/authid.go:84
v2ray.com/core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0xc00016e6a0, {0x92, 0x5, 0x5d, 0x4b, 0x26, 0xcf, 0xe5, 0xf3, 0xed, ...}, ...)
	v2ray.com/core/proxy/vmess/aead/authid.go:90 +0x50
v2ray.com/core/proxy/vmess.(*TimedUserValidator).Add(0xc000172e70, 0xc000165980)
	v2ray.com/core/proxy/vmess/validator.go:152 +0x365
v2ray.com/core/proxy/vmess/inbound.(*Handler).AddUser(0xc000174300, {0xb03000, 0x0}, 0x2)
	v2ray.com/core/proxy/vmess/inbound/inbound.go:166 +0x52
v2ray.com/core/proxy/vmess/inbound.New({0xd654c0, 0xc0001655f0}, 0xc00007f5e0)
	v2ray.com/core/proxy/vmess/inbound/inbound.go:133 +0x3b0
v2ray.com/core/proxy/vmess/inbound.init.2.func1({0xd654c0, 0xc0001655f0}, {0xc1a500, 0xc00007f5e0})
	v2ray.com/core/proxy/vmess/inbound/inbound.go:355 +0x3c
v2ray.com/core/common.CreateObject({0xd654c0, 0xc0001655f0}, {0xc1a500, 0xc00007f5e0})
	v2ray.com/core/common/type.go:32 +0x1a5
v2ray.com/core/app/proxyman/inbound.NewAlwaysOnInboundHandler({0xd654c0, 0xc0001655f0}, {0x0, 0x624e0}, 0xc000172e00, {0xc1a500, 0xc00007f5e0})
	v2ray.com/core/app/proxyman/inbound/always.go:52 +0x71
v2ray.com/core/app/proxyman/inbound.NewHandler({0xd654c0, 0xc0001655f0}, 0xc0001740c0)
	v2ray.com/core/app/proxyman/inbound/inbound.go:162 +0x2c5
v2ray.com/core/app/proxyman/inbound.init.0.func2({0xd654c0, 0xc0001655f0}, {0xc0cbc0, 0xc0001740c0})
	v2ray.com/core/app/proxyman/inbound/inbound.go:176 +0x3c
v2ray.com/core/common.CreateObject({0xd654c0, 0xc0001655f0}, {0xc0cbc0, 0xc0001740c0})
	v2ray.com/core/common/type.go:32 +0x1a5
v2ray.com/core.CreateObject(0x6, {0xc0cbc0, 0xc0001740c0})
	v2ray.com/core/functions.go:21 +0x78
v2ray.com/core.AddInboundHandler(0xc00007f0e0, 0x4)
	v2ray.com/core/v2ray.go:101 +0x65
v2ray.com/core.addInboundHandlers(0xc00007f0e0, {0xc000010fd0, 0x1, 0xc00007f0e0})
	v2ray.com/core/v2ray.go:117 +0x56
v2ray.com/core.initInstanceWithConfig(0xc000166fc0, 0xc00007f0e0)
	v2ray.com/core/v2ray.go:229 +0x42b
v2ray.com/core.New(0xc4ce5c)
	v2ray.com/core/v2ray.go:164 +0x77
main.startV2Ray()
	v2ray.com/core/main/main.go:115 +0x230
main.main()
	v2ray.com/core/main/main.go:139 +0x9f
```

## 如果 V2Ray 服务运行异常，请附上 journal 日志

 ```
Apr 17 09:46:54 iruru systemd[1]: Started V2Ray Service.
Apr 17 09:46:54 iruru v2ray[2678]: V2Ray 4.34.0 (user) 20220118-150717 (go1.17.6 linux/amd64)
Apr 17 09:46:54 iruru v2ray[2678]: A unified platform for anti-censorship.
Apr 17 09:46:54 iruru v2ray[2678]: panic: crypto/hmac: hash generation function does not produce unique values
Apr 17 09:46:54 iruru v2ray[2678]: goroutine 1 [running]:
Apr 17 09:46:54 iruru v2ray[2678]: crypto/hmac.New(0xc00015b5f0, {0xc00003ca38, 0x16, 0x18})
Apr 17 09:46:54 iruru v2ray[2678]:         crypto/hmac/hmac.go:143 +0x292
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.KDF({0xc000171bb0, 0x10, 0x10}, {0xc00015b640, 0x1, 0x10})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/kdf.go:13 +0x127
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.KDF16(...)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/kdf.go:22
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.NewCipherFromKey({0xc000171bb0, 0x618573, 0xc0000d2180})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/authid.go:41 +0x4a
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoder(...)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/authid.go:53
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/authid.go:84
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0xc00016e6a0, {0x92, 0x5, 0x5d, 0x4b>
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/aead/authid.go:90 +0x50
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess.(*TimedUserValidator).Add(0xc000172d20, 0xc0001659e0)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/validator.go:152 +0x365
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/inbound.(*Handler).AddUser(0xc000176280, {0xb03000, 0x0}, 0x2)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/inbound/inbound.go:166 +0x52
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/inbound.New({0xd654c0, 0xc000165650}, 0xc00007f5e0)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/inbound/inbound.go:133 +0x3b0
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/proxy/vmess/inbound.init.2.func1({0xd654c0, 0xc000165650}, {0xc1a500, 0xc00007f5e0})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/proxy/vmess/inbound/inbound.go:355 +0x3c
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/common.CreateObject({0xd654c0, 0xc000165650}, {0xc1a500, 0xc00007f5e0})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/common/type.go:32 +0x1a5
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/app/proxyman/inbound.NewAlwaysOnInboundHandler({0xd654c0, 0xc000165650}, {0x0, 0x624>
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/app/proxyman/inbound/always.go:52 +0x71
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/app/proxyman/inbound.NewHandler({0xd654c0, 0xc000165650}, 0xc000176040)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/app/proxyman/inbound/inbound.go:162 +0x2c5
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/app/proxyman/inbound.init.0.func2({0xd654c0, 0xc000165650}, {0xc0cbc0, 0xc000176040})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/app/proxyman/inbound/inbound.go:176 +0x3c
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core/common.CreateObject({0xd654c0, 0xc000165650}, {0xc0cbc0, 0xc000176040})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/common/type.go:32 +0x1a5
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core.CreateObject(0x6, {0xc0cbc0, 0xc000176040})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/functions.go:21 +0x78
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core.AddInboundHandler(0xc00007f0e0, 0x4)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/v2ray.go:101 +0x65
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core.addInboundHandlers(0xc00007f0e0, {0xc000010fd0, 0x1, 0xc00007f0e0})
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/v2ray.go:117 +0x56
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core.initInstanceWithConfig(0xc000166fc0, 0xc00007f0e0)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/v2ray.go:229 +0x42b
Apr 17 09:46:54 iruru v2ray[2678]: v2ray.com/core.New(0xc4ce5c)
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/v2ray.go:164 +0x77
Apr 17 09:46:54 iruru v2ray[2678]: main.startV2Ray()
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/main/main.go:115 +0x230
Apr 17 09:46:54 iruru v2ray[2678]: main.main()
Apr 17 09:46:54 iruru v2ray[2678]:         v2ray.com/core/main/main.go:139 +0x9f
Apr 17 09:46:54 iruru systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 17 09:46:54 iruru systemd[1]: v2ray.service: Failed with result 'exit-code'.
Apr 17 09:46:54 iruru systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Apr 17 09:46:54 iruru systemd[1]: Stopped V2Ray Service.
Apr 17 09:46:54 iruru systemd[1]: v2ray.service: Start request repeated too quickly.
Apr 17 09:46:54 iruru systemd[1]: v2ray.service: Failed with result 'exit-code'.
Apr 17 09:46:54 iruru systemd[1]: Failed to start V2Ray Service.
```

**Comment by sommio** [comment]
提这种上古版本问题会不会被暴打啊（

**Comment by AkinoKaede** [comment]
The key derivation function of VMess AEAD in V2Ray 4.34.0 will be broken if you build it with Go whose version is later than 1.15.

**Comment by AkinoKaede** [comment]
@rogers0 Here is the fixed key derivation function, do you have free time to add a patch to the package? 

https://github.com/v2fly/v2ray-core/blob/master/proxy/vmess/aead/kdf.go

**Comment by xiaokangwang** [comment]
This Debian specific bug have been reported to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009818

**Comment by sommio** [comment]
> This Debian specific bug have been reported to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009818

This problem also occurs with testing (bookworm), where the v2ray 4.34.0 in the bookworm repository is compiled with go1.17.6, as is the sid repository

**Comment by parsanoori** [comment]
I now have the problem by installing v2ray from [v2ray/jammy](https://packages.ubuntu.com/it/jammy/v2ray).
Is there any help beside deploying via docker?
