### ISSUE TITLE
v5核心使用dokodemo，运行时错误

### ISSUE THREAD

**Issue by SorenEricMent** [v2fly/v2ray-core#2277]
## 你正在使用哪个版本的 V2Ray？

客户端和服务端均为5.2.1

## 你的使用场景是什么？

使用v2ray dokodemo转发wireguard和vnc流量

## 你看到的异常现象是什么？

启动核心/测试配置 时在dokodemo模块发生运行时错误

## 你期待看到的正常表现是怎样的？

v2ray能够正常启动

## 请附上你的配置

```
{
    "inbounds": [
        {
            "protocol": "dokodemo-door",
            "address": "服务器IP",
            "port": 51820,
            "networks": "tcp, udp",
            "followRedirect": true,
            "tag": "wg"
        },
        {
            "protocol": "dokodemo-door",
            "address": "服务器IP",
            "port": 5900,
            "networks": "tcp, udp",
            "followRedirect": true,
            "tag": "vnc"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "protocol": "vmess",
            "settings": {
                "address": "服务器地址",
                "port": 端口,
                "uuid": "UUID"
            },
            "streamSettings": {
                //已经隐去
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "tag": "tun"
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "wg",
                    "vnc"
                ],
                "outboundTag": "tun"
            }
        ]
    }
}
```

## 请附上出错时软件输出的错误日志

已在后面给出

**服务器端错误日志：**

服务端不产生日志

**客户端错误日志：**

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x560002eeddc2]

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5/proxy/dokodemo.init.1.func2({0x560003803620, 0xc00047b410}, {0x560003757780?, 0xc000040eb0})
        github.com/v2fly/v2ray-core/v5/proxy/dokodemo/dokodemo.go:38 +0x82
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x560003803620, 0xc00047b410}, {0x560003757780, 0xc000040eb0})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.NewAlwaysOnInboundHandler({0x560003803620?, 0xc00047b410}, {0xc000126e7a, 0x2}, 0xc0001441c0, {0x560003757780?, 0xc000040eb0?})
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/always.go:52 +0x74
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.NewHandler({0x560003803620, 0xc00047b410}, 0xc000137720)
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/inbound.go:162 +0x2d0
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.init.0.func2({0x560003803620?, 0xc00047b410?}, {0x560003749900?, 0xc000137720?})
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/inbound.go:176 +0x3c
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x560003803620, 0xc00047b410}, {0x560003749900, 0xc000137720})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc000132e00?, {0x560003749900, 0xc000137720}, {0x56000372ffc0?, 0xc000132f80?})
        github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
github.com/v2fly/v2ray-core/v5.AddInboundHandler(0xc000427320, 0xc000137720)
        github.com/v2fly/v2ray-core/v5/v2ray.go:103 +0xad
github.com/v2fly/v2ray-core/v5.addInboundHandlers(...)
        github.com/v2fly/v2ray-core/v5/v2ray.go:119
github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc00017d290, 0xc000427320)
        github.com/v2fly/v2ray-core/v5/v2ray.go:236 +0x62c
github.com/v2fly/v2ray-core/v5.New(0x7ffe0a589c9c?)
        github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
github.com/v2fly/v2ray-core/v5/main/commands.executeRun(0x560003f01740, {0xc0000400c0, 0x3, 0x3})
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:82 +0xca
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
        github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
main.main()
        github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285
```

## 请附上访问日志

服务端不产生日志

## 其它相关的配置文件（如 Nginx）和相关日志

无

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x558772fd2dc2]

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5/proxy/dokodemo.init.1.func2({0x5587738e8620, 0xc0001988a0}, {0x55877383c780?, 0xc000040e10})
        github.com/v2fly/v2ray-core/v5/proxy/dokodemo/dokodemo.go:38 +0x82
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x5587738e8620, 0xc0001988a0}, {0x55877383c780, 0xc000040e10})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.NewAlwaysOnInboundHandler({0x5587738e8620?, 0xc0001988a0}, {0xc0001383aa, 0x2}, 0xc000162af0, {0x55877383c780?, 0xc000040e10?})
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/always.go:52 +0x74
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.NewHandler({0x5587738e8620, 0xc0001988a0}, 0xc000145680)
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/inbound.go:162 +0x2d0
github.com/v2fly/v2ray-core/v5/app/proxyman/inbound.init.0.func2({0x5587738e8620?, 0xc0001988a0?}, {0x55877382e900?, 0xc000145680?})
        github.com/v2fly/v2ray-core/v5/app/proxyman/inbound/inbound.go:176 +0x3c
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x5587738e8620, 0xc0001988a0}, {0x55877382e900, 0xc000145680})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc000142840?, {0x55877382e900, 0xc000145680}, {0x558773814fc0?, 0xc0001429e0?})
        github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
github.com/v2fly/v2ray-core/v5.AddInboundHandler(0xc00012afc0, 0xc000145680)
        github.com/v2fly/v2ray-core/v5/v2ray.go:103 +0xad
github.com/v2fly/v2ray-core/v5.addInboundHandlers(...)
        github.com/v2fly/v2ray-core/v5/v2ray.go:119
github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc0001fa510, 0xc00012afc0)
        github.com/v2fly/v2ray-core/v5/v2ray.go:236 +0x62c
github.com/v2fly/v2ray-core/v5.New(0x7ffdb0162c9b?)
        github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
github.com/v2fly/v2ray-core/v5/main/commands.executeTest(0x558773fe6800, {0xc0000400c0, 0x3, 0x3})
        github.com/v2fly/v2ray-core/v5/main/commands/test.go:54 +0x8b
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
        github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
main.main()
        github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285

```

**Comment by SorenEricMent** [comment]
发现原因了 少加了settings....
