### ISSUE TITLE
panic: runtime error: slice bounds out of range [:2507] with capacity 2048

### ISSUE THREAD

**Issue by darren** [v2fly/v2ray-core#2343]
## What version of V2Ray are you using?

5.4.0
e9943b5a7295ca76341c996a4937f7e03a5015f9

## What problems have you encountered?

```go
panic: runtime error: slice bounds out of range [:2507] with capacity 2048
goroutine 25 [running]:
github.com/v2fly/v2ray-core/v5/common/buf.(*Buffer).Bytes(...)
        /home/darren/Sources/v2ray-core/common/buf/buffer.go:103
github.com/v2fly/v2ray-core/v5/common/buf.WriteMultiBuffer({0x7f3181440ac0, 0xc00129a000}, {0xc0004ea078?, 0xc000073db8?, 0x83b665?})
        /home/darren/Sources/v2ray-core/common/buf/multi_buffer.go:215 +0x16a
github.com/v2fly/v2ray-core/v5/common/buf.(*SequentialWriter).WriteMultiBuffer(0x1?, {0xc0004ea078?, 0xc000014090?, 0xc00172c660?})
        /home/darren/Sources/v2ray-core/common/buf/writer.go:222 +0x38
github.com/v2fly/v2ray-core/v5/common/buf.copyInternal({0x12f4620, 0xc000014078}, {0x12f2f40, 0xc000c7c090}, 0xc000012270)
        /home/darren/Sources/v2ray-core/common/buf/copy.go:87 +0x175
github.com/v2fly/v2ray-core/v5/common/buf.Copy({0x12f4620, 0xc000014078}, {0x12f2f40, 0xc000c7c090}, {0xc00172c738, 0x1, 0x0?})
        /home/darren/Sources/v2ray-core/common/buf/copy.go:104 +0xa5
github.com/v2fly/v2ray-core/v5/proxy/dokodemo.(*Door).Process.func4()
        /home/darren/Sources/v2ray-core/proxy/dokodemo/dokodemo.go:209 +0xef
github.com/v2fly/v2ray-core/v5/common/task.Run.func1(0x0?)
        /home/darren/Sources/v2ray-core/common/task/task.go:28 +0x2e
created by github.com/v2fly/v2ray-core/v5/common/task.Run
        /home/darren/Sources/v2ray-core/common/task/task.go:27 +0xde
```

PS：本地未做任何修改 panic确实发生了 暂时找不到重现panic的具体配置和步骤

**Comment by Vigilans** [comment]
> github.com/v2fly/v2ray-core/v5/proxy/dokodemo.(*Door).Process.func4()
>        v2ray-core/proxy/dokodemo/dokodemo.go:209 +0xef

https://github.com/v2fly/v2ray-core/blob/e9943b5a7295ca76341c996a4937f7e03a5015f9/proxy/dokodemo/dokodemo.go#L206-L213

* Error occured on outbound trying to write reponse back to dokodemo door. 
* Since dokodemo's receiver is `SequentialWriter`, the connection is using UDP.
* Problem seems to be the UDP payload written back from outbound has size 2507, exceeding the underlying buffer size 2048.

So config file is needed to know which outbound may be replying, and diagnose how a buffer of 2048 bytes holding payload of 2507 could be created.

**Comment by darren** [comment]
@Vigilans Thanks!

The outbounds are vless over mkcp:
```json
{
  "outbounds": [
    {
      "mux": {
        "enabled": true
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "[:]",
            "port": 8080,
            "users": [
              {
                "alterId": 64,
                "encryption": "none",
                "id": "xxx",
                "level": 1
              }
            ]
          },
          {
            "address": "[:]",
            "port": 8080,
            "users": [
              {
                "alterId": 64,
                "encryption": "none",
                "id": "xxx",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "kcpSettings": {
          "congestion": true,
          "downlinkCapacity": 50,
          "header": {
            "type": "utp"
          },
          "mtu": 1350,
          "seed": "xxx",
          "tti": 20,
          "uplinkCapacity": 20
        },
        "network": "mkcp"
      },
      "tag": "xxx"
    }
  ]
}
```

**Comment by AkinoKaede** [comment]
This seems puzzling, and generally speaking, unless you're networking with jumbo frames, there won't be any UDP datagrams larger than 1500 bytes.
