### ISSUE TITLE
FakeDNSEngine panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [v2fly/v2ray-core#2568]
## What version of V2Ray are you using?

5.7.0

## What's your scenario of using V2Ray?

tproxy=>v2ray systemd

## What problems have you encountered?

crash on start

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

## If V2Ray service is abnormal, please attach journal log here

```
sudo systemctl restart v2ray && sudo journalctl -f -t v2ray
-- Journal begins at Wed 2023-06-21 --
v2ray[151723]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[151723]: A unified platform for anti-censorship.
v2ray[151723]: Configuration OK.
v2ray[151747]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[151747]: A unified platform for anti-censorship.
v2ray[151747]: panic: runtime error: invalid memory address or nil pointer dereference
v2ray[151747]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d5dc0]
v2ray[151747]: goroutine 36 [running]:
v2ray[151747]: net.networkNumberAndMask(0x203000?)
v2ray[151747]:         net/ip.go:498
v2ray[151747]: net.(*IPNet).Contains(0xc001e3e340?, {0xc001e3e3a0, 0x10, 0xc001fbc4f8?})
v2ray[151747]:         net/ip.go:522 +0x27
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc001e3a5d0, {0x1363088, 0xc001e3e340})
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x66
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc001e4a2d0?, {0x1363088, 0xc001e3e340})
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x69
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x1361680, 0xc001e4a2d0}, {0xc001e1fa90?, 0x5?, 0x5?})
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0xa5
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc000012780, {0x1361680, 0xc001e4a2d0})
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:94 +0x1e6
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x1361680, 0xc001e4a2d0}, 0x0?, 0x0, 0x0?)
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:247 +0x133
v2ray[151747]: github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:223 +0x134
v2ray[151747]: created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch
v2ray[151747]:         github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:218 +0x34a
v2ray[151796]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[151796]: A unified platform for anti-censorship.
v2ray[151796]: Configuration OK.
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```rust
V2Ray 5.32.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.24.3 linux/amd64)
A unified platform for anti-censorship.
Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f8660]

goroutine 51 [running]:
net.networkNumberAndMask(0xc000d89c28?)
        net/ip.go:457
net.(*IPNet).Contains(0xc000b14010?, {0xc000b14060, 0x10, 0xc000d89ca0?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc0008b2690, {0x19eed48, 0xc000b14010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x65
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc000b00330?, {0x19eed48, 0xc000b14010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19eebf8, 0xc000b00330}, {0x8000?, 0xc000d89d88?, 0x1628ce0?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x92
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc00067e1b0, {0x19eebf8, 0xc000b00330})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x143
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19eebf8, 0xc000b00330}, 0xc000b003c0, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x111
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10b
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 50
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```rust
V2Ray 5.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.24.4 linux/amd64)
A unified platform for anti-censorship.
Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f8940]

goroutine 95 [running]:
net.networkNumberAndMask(0xc000996c28?)
        net/ip.go:457
net.(*IPNet).Contains(0xc00086e070?, {0xc00086e0f0, 0x10, 0xc0006f44a0?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc0005b8030, {0x19f6c88, 0xc00086e070})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x65
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc000857290?, {0x19f6c88, 0xc00086e070})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19f6b38, 0xc000857290}, {0x8000?, 0xc0006f4588?, 0x162f760?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x92
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc0008548d0, {0x19f6b38, 0xc000857290})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x143
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19f6b38, 0xc000857290}, 0xc000857980, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x111
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10b
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 88
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f8940]

goroutine 52 [running]:
net.networkNumberAndMask(0xc00011ac28?)
        net/ip.go:457
net.(*IPNet).Contains(0xc000720000?, {0xc000720034, 0x4, 0xc000653ca0?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc0005b8030, {0x19f6c50, 0xc000720000})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x65
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc0007141e0?, {0x19f6c50, 0xc000720000})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19f6b38, 0xc0007141e0}, {0x8000?, 0xc000653d88?, 0x162f760?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x92
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc0007121f8, {0x19f6b38, 0xc0007141e0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x143
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19f6b38, 0xc0007141e0}, 0xc000714240, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x111
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10b
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 81
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f8940]

goroutine 97 [running]:
net.networkNumberAndMask(0xc000874c28?)
        net/ip.go:457
net.(*IPNet).Contains(0xc000986000?, {0xc000986050, 0x10, 0xc000861ca0?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc0005b8030, {0x19f6c88, 0xc000986000})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x65
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc0009841b0?, {0x19f6c88, 0xc000986000})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19f6b38, 0xc0009841b0}, {0x8000?, 0xc000861d88?, 0x162f760?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x92
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc0009821e0, {0x19f6b38, 0xc0009841b0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x143
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19f6b38, 0xc0009841b0}, 0xc000984210, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x111
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10b
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 87
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Not stale, still the current version is unstable and crashing.
```rust

V2Ray 5.41.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.24.2 linux/amd64)
A unified platform for anti-censorship.
Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6fa9c0]

goroutine 67 [running]:
net.networkNumberAndMask(0xc00099ac28?)
        net/ip.go:457
net.(*IPNet).Contains(0xc0005f201c?, {0xc0005f2048, 0x4, 0xc00099aca0?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0xc0004aedb0, {0x199c200, 0xc0005f201c})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x65
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0xc0005e2690?, {0x199c200, 0xc0005f201c})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x199c0e8, 0xc0005e2690}, {0x8000?, 0xc00099ad88?, 0x15c5040?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x92
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0xc0000105b8, {0x199c0e8, 0xc0005e2690})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x143
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x199c0e8, 0xc0005e2690}, 0xc0005e26f0, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x111
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10b
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 52
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
same error in V2Ray 5.47.0

```ts
V2Ray 5.47.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6fe980]

goroutine 82 [running]:
net.networkNumberAndMask(0x166681e1bc28?)
        net/ip.go:457
net.(*IPNet).Contains(0x166681632004?, {0x166681632050, 0x4, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x166681bb5e60, {0x18eef20, 0x166681632004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x1666816262d0?, {0x18eef20, 0x166681632004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x18eee08, 0x1666816262d0}, {0x1666816262d0?, 0x8000?, 0x169e8a0?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x166681624180, {0x18eee08, 0x1666816262d0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x18eee08, 0x1666816262d0}, 0x166681626360, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 81
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
same in V2Ray 5.48.0
```ts

V2Ray 5.48.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6fea20]

goroutine 21 [running]:
net.networkNumberAndMask(0x5438ff01c28?)
        net/ip.go:457
net.(*IPNet).Contains(0x5438ff12004?, {0x5438ff12050, 0x4, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x5438fe3f3e0, {0x1923660, 0x5438ff12004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x5438fc7e300?, {0x1923660, 0x5438ff12004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x1923548, 0x5438fc7e300}, {0x5438fc7e300?, 0x8000?, 0x16ce1c0?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x5438fa88258, {0x1923548, 0x5438fc7e300})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x1923548, 0x5438fc7e300}, 0x5438fc7e390, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 20
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```ts
V2Ray 5.49.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6feb40]

goroutine 66 [running]:
net.networkNumberAndMask(0x4e262936c28?)
        net/ip.go:457
net.(*IPNet).Contains(0x4e2635a8004?, {0x4e2635a8054, 0x4, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x4e2630eb230, {0x19b0840, 0x4e2635a8004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x4e2635a0300?, {0x19b0840, 0x4e2635a8004})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19b0728, 0x4e2635a0300}, {0x4e2635a0300?, 0x8000?, 0x174b080?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x4e262ea0a38, {0x19b0728, 0x4e2635a0300})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19b0728, 0x4e2635a0300}, 0x4e2635a0390, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 65
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
3 years later V2Ray 5.51.2 still unstable reproduceable panic:
- #2972

```go

V2Ray 5.51.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6feb40]

goroutine 82 [running]:
net.networkNumberAndMask(0x39f869c8fc28?)
        net/ip.go:457
net.(*IPNet).Contains(0x39f869b04010?, {0x39f869b04070, 0x10, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x39f869c914a0, {0x19ca878, 0x39f869b04010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x39f86a5f63f0?, {0x19ca878, 0x39f869b04010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19ca728, 0x39f86a5f63f0}, {0x39f86a5f63f0?, 0x8000?, 0x1761560?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x39f86a75a198, {0x19ca728, 0x39f86a5f63f0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19ca728, 0x39f86a5f63f0}, 0x39f86a5f6480, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 81
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325

V2Ray 5.51.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6feb40]

goroutine 90 [running]:
net.networkNumberAndMask(0x1cc55cb0bc28?)
        net/ip.go:457
net.(*IPNet).Contains(0x1cc55c902028?, {0x1cc55c9020c4, 0x4, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x1cc55d313470, {0x19ca840, 0x1cc55c902028})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x1cc55d0353e0?, {0x19ca840, 0x1cc55c902028})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19ca728, 0x1cc55d0353e0}, {0x1cc55d0353e0?, 0x8000?, 0x1761560?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x1cc55d038e10, {0x19ca728, 0x1cc55d0353e0})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19ca728, 0x1cc55d0353e0}, 0x1cc55d035ce0, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 100
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325

V2Ray 5.51.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.26.1 linux/amd64)
A unified platform for anti-censorship.
 Using confdir from env: /etc/v2ray
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6feb40]

goroutine 98 [running]:
net.networkNumberAndMask(0x29fb38018c28?)
        net/ip.go:457
net.(*IPNet).Contains(0x29fb381a8010?, {0x29fb381a8070, 0x10, 0x18?})
        net/ip.go:481 +0x25
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetDomainFromFakeDNS(0x29fb381471d0, {0x19ca878, 0x29fb381a8010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:139 +0x5f
github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetDomainFromFakeDNS(...)
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:182
github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSEngine).GetDomainFromFakeDNS(0x29fb388de420?, {0x19ca878, 0x29fb381a8010})
        github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:61 +0x65
github.com/v2fly/v2ray-core/v5/app/dispatcher.newFakeDNSSniffer.func1({0x19ca728, 0x29fb388de420}, {0x29fb388de420?, 0x8000?, 0x1761560?})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/fakednssniffer.go:34 +0x90
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*Sniffer).SniffMetadata(0x29fb389e41c8, {0x19ca728, 0x29fb388de420})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/sniffer.go:98 +0x16c
github.com/v2fly/v2ray-core/v5/app/dispatcher.sniffer({0x19ca728, 0x29fb388de420}, 0x29fb388de4b0, 0x1, 0x2)
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:252 +0x105
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:227 +0x10a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 97
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:222 +0x325
```
