### ISSUE TITLE
Config failed to be loaded after v5.7.0

### ISSUE THREAD

**Issue by Ninlives** [v2fly/v2ray-core#2794]
## What version of V2Ray are you using?

v5.7.0 works, later versions do not work.

## What problems have you encountered?

v2ray client failed to start because of panic while loading config.

## What's your expectation?

v2ray client starts normally

## Please attach your configuration here

**Client configuration:**

```javascript
{
  "inbounds": [
    {
      "port": 9080,
      "protocol": "http",
      "settings": {
        "allowTransparent": false
      },
      "tag": "http"
    },
    {
      "port": 1081,
      "protocol": "dokodemo-door",
      "settings": {
        "followRedirect": true,
        "network": "tcp,udp"
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "redirect"
        }
      },
      "tag": "transparent"
    },
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": false
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "proxy"
    },
    {
      "port": 1082,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": false
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "acl"
    }
  ],
  "log": {
    "access": "/tmp/v2ray_access.log",
    "error": "/tmp/v2ray_error.log",
    "loglevel": "info"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "streamSettings": {
        "sockopt": {
          "mark": 187
        }
      },
      "tag": "direct"
    },
    {
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "<hidden>",
            "level": 0,
            "password": "<hidden>",
            "port": 443
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "sockopt": {
          "mark": 187
        },
        "wsSettings": {
          "path": "<hidden>"
        }
      },
      "tag": "proxy"
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "domains": [
          "regexp:\\.onion$"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "domains": [
          "geosite:cn"
        ],
        "inboundTag": [
          "acl"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "inboundTag": [
          "acl"
        ],
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "inboundTag": [
          "acl",
          "proxy",
          "transparent",
          "http"
        ],
        "outboundTag": "proxy",
        "type": "field"
      }
    ]
  }
}

```

## If V2Ray service is abnormal, please attach journal log here

```
V2Ray 5.11.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
A unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x118a01e]
goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5/infra/conf/v2jsonpb.(*V2JsonProtobufFollowerFieldDescriptor).Number(0x0?)
        <autogenerated>:1 +0x1e
google.golang.org/protobuf/encoding/protojson.decoder.unmarshalMessage
        google.golang.org/protobuf@v1.31.0/encoding/protojson/decode.go:201 +0x885
google.golang.org/protobuf/encoding/protojson.UnmarshalOptions.unmarshal
        google.golang.org/protobuf@v1.31.0/encoding/protojson/decode.go:72 +0x171
google.golang.org/protobuf/encoding/protojson.UnmarshalOptions.Unmarshal(...)
        google.golang.org/protobuf@v1.31.0/encoding/protojson/decode.go:58
github.com/v2fly/v2ray-core/v5/infra/conf/v2jsonpb.loadV2JsonPb
        github.com/v2fly/v2ray-core/v5/infra/conf/v2jsonpb/v2jsonpb.go:21 +0x137
github.com/v2fly/v2ray-core/v5/infra/conf/v2jsonpb.init.0.func1
        github.com/v2fly/v2ray-core/v5/infra/conf/v2jsonpb/v2jsonpb.go:58 +0x78
github.com/v2fly/v2ray-core/v5.loadSingleConfigByTryingAllLoaders
        github.com/v2fly/v2ray-core/v5/config.go:174 +0xa7
github.com/v2fly/v2ray-core/v5.loadSingleConfigAutoFormatFromFile
        github.com/v2fly/v2ray-core/v5/config.go:164 +0x194
github.com/v2fly/v2ray-core/v5.loadSingleConfigAutoFormat
        github.com/v2fly/v2ray-core/v5/config.go:140 +0xa5
github.com/v2fly/v2ray-core/v5.LoadConfig
        github.com/v2fly/v2ray-core/v5/config.go:110 +0x125
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:194 +0x4c
github.com/v2fly/v2ray-core/v5/main/commands.executeRun
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:81 +0xc5
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
        github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x5fd
main.main()
        github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285
```

**Comment by Ninlives** [comment]
Still important to me.
