### ISSUE TITLE
V2Ray 使用vlite导致v2ray崩溃

### ISSUE THREAD

**Issue by Yhaiyang** [v2fly/v2ray-core#2851]
## 你正在使用哪个版本的 V2Ray？

V2Ray 5.13.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
A unified platform for anti-censorship.

## 你看到的异常现象是什么？

client崩溃

## 你期待看到的正常表现是怎样的？

连接正常

## 请附上你的配置

**服务端配置：**

```javascript
    {
      "port":"8089",
      "listen":"0.0.0.0",
      "protocol":"vliteu",
      "tag":"vlite_in",
      "settings":{
        "password":"8031933c-ea45-4ed3-88bf-43c2f66298d0",
        "scramblePacket": false,
        "enableFec": false,
        "enableStabilization": false,
        "enableRenegotiation": false,
        "handshakeMaskingPaddingSize": 1350
      },
      "sniffing":{
        "enabled":false
      }
    }

```

**客户端配置：**

```javascript

"inbounds": [
      {
        "port":"57184",
        "listen":"0.0.0.0",
        "protocol":"dokodemo-door",
        "tag":"dokodemo_in",
        "settings":{
          "networks": "udp",
          "port": 7184,
          "address": "---------------------------"
        },
        "sniffing":{
          "enabled":false
        }
      }
    ],
    "outbounds": [
    {
        "protocol": "vliteu",
        "settings": {
          "address": "-----------",
          "port": "8089",
          "password": "8031933c-ea45-4ed3-88bf-43c2f66298d0",
          "scramblePacket": false,
          "enableFec": false,
          "enableStabilization": false,
          "enableRenegotiation": false,
          "handshakeMaskingPaddingSize": 1350
        },
        "sendThrough": "0.0.0.0",
        "tag": "vlite_out",
        "mux": {
          "enabled": false,
          "concurrency": 8
        }
      }
    ],
    "router": {
        "rule": [
          {
            "inboundTag": ["dokodemo_in"],
            "tag": "vlite_out"
          }
        ]
    }

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript


```

**客户端错误日志：**

```javascript

runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x13
github.com/xiaokangwang/VLite/transport/packetsctp/sctprelay.(*PacketSCTPRelay).tlsopenClient(0xc0004d6be0)
        github.com/xiaokangwang/VLite@v0.0.0-20220418190619-cff95160a432/transport/packetsctp/sctprelay/relay.go:171 +0x2b3
github.com/xiaokangwang/VLite/transport/packetsctp/sctprelay.NewPacketRelayClient({0x177b6c8?, 0xc00081a050}, 0xc0003a84e0, 0xc0003a8540, 0xc0003a85a0, {0xc0004dea50, 0x24, 0x30}, {0x1770430, 0xc0000aebd0})
        github.com/xiaokangwang/VLite@v0.0.0-20220418190619-cff95160a432/transport/packetsctp/sctprelay/relay.go:59 +0x111
github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound.enableInterface(0xc000141d40)
        github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound/outbound.go:212 +0x6c8
github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound.(*Handler).ensureStarted(0xc0003a2870?, 0x1297a20?)
        github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound/outbound.go:91 +0x96
github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound.(*Handler).Process(0xc000469480, {0x1770430, 0xc0003a2c90}, 0xc0004ec400, {0x0?, 0x0?})
        github.com/v2fly/v2ray-core/v5/proxy/vlite/outbound/outbound.go:58 +0xdb
github.com/v2fly/v2ray-core/v5/app/proxyman/outbound.(*Handler).Dispatch(0xc00037c990, {0x1770430?, 0xc0003a2c90?}, 0xc0004ec400)
        github.com/v2fly/v2ray-core/v5/app/proxyman/outbound/handler.go:174 +0x3f5
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00037e0c0, {0x1770430, 0xc0003a2c90}, 0xc0004ec400, {{0x1770158, 0xc000469150}, 0x1c10, 0x3})
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:336 +0x90d
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 23
        github.com/v2fly/v2ray-core/v5/app/dispatcher/default.go:216 +0x439
2024/01/10 15:01:31 Over DTLS Handshake
2024/01/10 15:01:31 Begin SCTP Handshake
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe86dbf]

goroutine 31 [running]:
github.com/pion/dtls/v2.(*Conn).isHandshakeCompletedSuccessfully(...)
        github.com/pion/dtls/v2@v2.2.7/conn.go:823
github.com/pion/dtls/v2.(*Conn).Read(0x7effacfcbb58?, {0xc0005a0000?, 0xc000382e40?, 0x41900b?})
        github.com/pion/dtls/v2@v2.2.7/conn.go:296 +0x1f
github.com/xiaokangwang/VLite/transport/filteredConn.(*FilteredConn).Read(0xc000818370, {0xc000484000, 0x2000, 0xc0003923a0?})
        github.com/xiaokangwang/VLite@v0.0.0-20220418190619-cff95160a432/transport/filteredConn/conn.go:147 +0x74
github.com/pion/sctp.(*Association).readLoop(0xc000396000)
        github.com/pion/sctp@v1.8.7/association.go:532 +0x14b
created by github.com/pion/sctp.(*Association).init in goroutine 24
        github.com/pion/sctp@v1.8.7/association.go:342 +0xbe

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by freebat** [comment]
V2Ray 5.13.0  server running   infra/conf/cfgcommon/loader: unknown config id: vliteu   ?  how to fix

**Comment by Yhaiyang** [comment]
use config format jsonv5
