### ISSUE TITLE
Failed to run Core, please see the log

### ISSUE THREAD

**Issue by AhrimanSefid** [v2fly/v2ray-core#3250]
2024-12-09 22:38:15.3794-DEBUG ,
2024-12-09 22:38:15.3794-DEBUG    at ServiceLib.Handler.CoreHandler.RunProcess(CoreInfo coreInfo, String configPath, Boolean displayLog, Boolean mayNeedSudo)
2024-12-09 22:38:16.7462-DEBUG ,
2024-12-09 22:38:16.7462-DEBUG    at ServiceLib.Handler.CoreHandler.RunProcess(CoreInfo coreInfo, String configPath, Boolean displayLog, Boolean mayNeedSudo)

![image](https://github.com/user-attachments/assets/a9012531-207e-4ebf-a422-58102c94f23d)

**Comment by AkinoKaede** [comment]
Although it may sound a bit unusual, v2rayN does not use V2Ray by default. So it's not caused by V2Ray.
