### ISSUE TITLE
Trojan panic: write unix /tmp/v2ray-trojan-ws-tls.socket->@: write: broken pipe

### ISSUE THREAD

**Issue by kslr** [v2fly/v2ray-core#495]
```bash
V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)
A unified platform for anti-censorship.
2020/12/08 15:52:02 [Info] v2ray.com/core/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
panic: write unix /tmp/v2ray-trojan-ws-tls.socket->@: write: broken pipe

goroutine 362890 [running]:
v2ray.com/core/common.Must(...)
        v2ray.com/core/common/common.go:26
v2ray.com/core/proxy/trojan.(*Server).handleUDPPayload.func1(0xf7c420, 0xc000ed8bc0, 0xc000ed8cc0)
        v2ray.com/core/proxy/trojan/server.go:210 +0xb4
v2ray.com/core/transport/internet/udp.handleInput(0xf7c420, 0xc000ed8bc0, 0xc000da3480, 0xf7d8e0, 0xc000b49bc8, 0x30000007b, 0xc000bb5580)
        v2ray.com/core/transport/internet/udp/dispatcher.go:116 +0xb2
created by v2ray.com/core/transport/internet/udp.(*Dispatcher).getInboundRay
        v2ray.com/core/transport/internet/udp/dispatcher.go:77 +0x547
```

**Comment by maskedeken** [comment]
怎么重现？

**Comment by 0x0404** [comment]
#### 运行环境

Debian10-x86_64，V2Ray 4.33.0

#### 运行方式

nginx在前解析tls，通过Unix domain socket代理转发给后端v2ray。

#### 异常现象

长时间运行后，有可能出现broken pipe，具体时间不确定（大概要用几个小时，加大udp传送数据量可能提早出现，也可能和线路状况有关）。可通过V2ray挂strace复现。

#### v2ray 客户端配置文件

```
{
    "inbounds": [
        {
            "tag":"transparent",
            "listen": "127.0.0.1",
            "port": "12345",
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            }
        },
        {
            "port": 10800,
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "udp": true,
                "auth": "noauth"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "proxy",
            "protocol": "trojan",
            "settings": {
                "servers": [
                    {
                        "address": "x.x.x.x",
                        "port": 443,
                        "password": "xxxxxxxxxxxxxxxxxxxxx",
                        "level": 0
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "path": "/xxxxxxxxx",
                    "headers": {
                        "Host": "xxx.xxx.com"
                    }
                },
                "tlsSettings": {
                    "serverName": "xxx.xxx.com"
                }
            }
        },
        {
            "tag": "direct",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "protocol": "freedom"
        }
    ]
}
```

#### v2ray 服务端配置文件

```
{
    "inbounds": [
        {
            "listen": "/tmp/v2ray-trojan-ws-tls.socket",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "xxxxxxxxxxxxxxxxxxxxx",
                        "level": 0
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 80
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "headers": {
                        "Host": "xxx.xxx.com"
                    },
                    "acceptProxyProtocol": false,
                    "path": "/xxxxxxxxx"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

```
#### nginx配置文件
```
server{
    server_name xxx.xxx.com;
    access_log  /var/log/nginx/${host}.log  main;

    location /xxxxxxxxx {
        access_log off;
        proxy_redirect off;
        proxy_pass http://unix:/tmp/v2ray-trojan-ws-tls.socket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        # Show realip in v2ray access.log
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate /etc/nginx/certificate/xxx.xxx.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/certificate/xxx.xxx.com/privkey.key;
    ssl_session_cache shared:le_nginx_SSL:1m;
    ssl_session_timeout 1440m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA";
}

server{
    server_name xxx.xxx.com;
    access_log  /var/log/nginx/${host}.log  main;

    listen 80;
}
```

**Comment by 0x0404** [comment]
采用上述方式代理转发时，记得把Unix domain socket文件赋予适当的权限，V2ray默认生成的socket文件权限很奇怪，有可能导致nginx没有访问权限。
