### ISSUE TITLE
服务端 panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by zhj9709** [v2fly/v2ray-core#622]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.33.0
4.34.0

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
v2rayN，一直全局代理

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
进程panic了

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
{
  "log": {
    //"access": "/var/log/v2ray/access.log",
    //"error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 22451,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxx",
            "level": 1,
            "alterId": 16
          }
        ]
      },
      "streamSettings": {
        "security": "none",
        "network": "tcp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

```

Client configuration:

```javascript
    // Please attach your client configuration here.
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10081,
      "listen": "0.0.0.0",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": false,
        "allowTransparent": false
      }
    },
    {
      "tag": "api",
      "port": 4536,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1",
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxxx",
            "port": 22451,
            "users": [
              {
                "id": "xxxxxxx",
                "alterId": 16,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": {
    "servers": [
      "114.114.114.114",
      "8.8.8.8"
    ]
  },
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
Jan 19 01:52:58 lt v2ray[5498]: panic: runtime error: slice bounds out of range [:-14]
Jan 19 01:52:58 lt v2ray[5498]: goroutine 5432420 [running]:
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf.(*Buffer).BytesTo(...)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf/buffer.go:110
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto.(*AuthenticationReader).readBuffer(0xc02277cf00, 0x2e00000010, 0x0, 0x0, 0x80)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto/auth.go:140 +0x33f
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto.(*AuthenticationReader).readInternal(0xc02277cf00, 0x0, 0xc0035e7d78, 0x0, 0x0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto/auth.go:176 +0x125
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto.(*AuthenticationReader).ReadMultiBuffer(0xc02277cf00, 0xc01ea89700, 0x1, 0x10, 0x0, 0x0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/crypto/auth.go:205 +0x85
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf.copyInternal(0xf9f2a0, 0xc02277cf00, 0xfa04a0, 0xc0142c6e20, 0xc002e6e480, 0xc002db1001, 0xc002e6e440)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf/copy.go:81 +0x49
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf.Copy(0xf9f2a0, 0xc02277cf00, 0xfa04a0, 0xc0142c6e20, 0xc0035e7f38, 0x1, 0x1, 0x0, 0xc00f3ef9e0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/buf/copy.go:104 +0xa8
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/proxy/vmess/inbound.(*Handler).Process.func1(0x0, 0x0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/proxy/vmess/inbound/inbound.go:289 +0x147
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/task.OnSuccess.func1(0xc000034400, 0x0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/task/task.go:12 +0x2f
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/task.Run.func1(0xc0142c6e48, 0xc02277cea0, 0xc002e6e2c0)
Jan 19 01:52:58 lt v2ray[5498]: v2ray.com/core/common/task/task.go:28 +0x2b
Jan 19 01:52:58 lt v2ray[5498]: created by v2ray.com/core/commo
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by database64128** [comment]
Not following template, not enough information, then no solutions.

**Comment by zhj9709** [comment]
@database64128 

![image](https://user-images.githubusercontent.com/13991774/105942218-c10c3e80-6099-11eb-892a-49e22190f695.png)

**Comment by database64128** [comment]
> @database64128
> 
> ![image](https://user-images.githubusercontent.com/13991774/105942218-c10c3e80-6099-11eb-892a-49e22190f695.png)

The quoted change doesn't seem like a good way to mitigate the issue. Please elaborate.

**Comment by kslr** [comment]
Can you provide all panic logs?

**Comment by zhj9709** [comment]
> Can you provide all panic logs?

![image](https://user-images.githubusercontent.com/13991774/105981220-d05aae80-60d0-11eb-9b14-d108ec2ed1e0.png)

![image](https://user-images.githubusercontent.com/13991774/105981507-1dd71b80-60d1-11eb-9f8b-cda466775e68.png)

只能找到这个了

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/106345604-6880af80-62ec-11eb-90af-0299d440c6f6.png)
![image](https://user-images.githubusercontent.com/13991774/106345606-6caccd00-62ec-11eb-85b4-94ac526fe356.png)
[access.log](https://raw.githubusercontent.com/zhj9709/issues/master/v2fly/622/access.log)
