### ISSUE TITLE
panic: V is not in context.

### ISSUE THREAD

**Issue by rurirei** [v2fly/v2ray-core#698]
i uses v2ray-core (commit top to #406 merged) as a Android library (code as below) and met errors as below, **but do not met this** if uses tree before FakeDns added. especially `fakednssniffer.go` appears at logs, maybe that is introduced by FakeDns commits? sorry for my not read codes of FakeDns.
```golang
[v2ray] [Warning] v2ray.com/core: V2Ray 4.34.0 started

[tun2socks] [Handle] tcp 172.19.0.1:41201 147.202.171.5:443 147.202.171.5:443

panic: V is not in context.

goroutine 31 [running]:

v2ray.com/core.MustFromContext(0x7dea651aa0, 0x4002cb94d0, 0x10)
	/home/runner/go/src/v2ray.com/core/context.go:26 +0x8c

v2ray.com/core.RequireFeatures(0x7dea651aa0, 0x4002cb94d0, 0x7dea471ce0, 0x4002638d40, 0x30, 0x7dea47c760)
	/home/runner/go/src/v2ray.com/core/v2ray.go:154 +0x28

v2ray.com/core/app/dispatcher.newFakeDNSSniffer(0x7dea651aa0, 0x4002cb94d0, 0x4002d8c070, 0x7de9f685f0, 0x7dea462280, 0x400000f460)
	/home/runner/go/src/v2ray.com/core/app/dispatcher/fakednssniffer.go:18 +0x88

v2ray.com/core/app/dispatcher.NewSniffer(0x7dea651aa0, 0x4002cb94d0, 0x400000f460)
	/home/runner/go/src/v2ray.com/core/app/dispatcher/sniffer.go:41 +0xa8

v2ray.com/core/app/dispatcher.sniffer(0x7dea651aa0, 0x4002cb94d0, 0x4002cb9590, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/src/v2ray.com/core/app/dispatcher/default.go:252 +0xb4

v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1(0x400000f3c0, 0x7dea651aa0, 0x4002cb94d0, 0x400000f320, 0x2, 0x2, 0x7e00960001, 0x4000ead3c0, 0x400000f340, 0x4002cb94a0, ...)
	/home/runner/go/src/v2ray.com/core/app/dispatcher/default.go:232 +0x90

created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
	/home/runner/go/src/v2ray.com/core/app/dispatcher/default.go:227 +0x4f8
```
```golang
import (
    "context"

    vcore "v2ray.com/core"
    vnet "v2ray.com/core/common/net"
    vproxyman "v2ray.com/core/app/proxyman"
    vprotocol "v2ray.com/core/common/protocol"
    vsession "v2ray.com/core/common/session"
)

    vinbound := &vsession.Inbound{Tag: "vinbound"}

    vsniffing := &vproxyman.SniffingConfig{
        Enabled:             true,
        DestinationOverride: []string{"http", "tls"},
        MetadataOnly:        false,
    }

    vcontent := &vsession.Content{
        SniffingRequest: vsession.SniffingRequest{
            Enabled:                        vsniffing.Enabled,
            OverrideDestinationForProtocol: vsniffing.DestinationOverride,
            MetadataOnly:                   vsniffing.MetadataOnly,
        },
    }

    ctx := vsession.ContextWithID(context.Background(), vsession.NewID())
    ctx = vsession.ContextWithInbound(ctx, vinbound)
    ctx = vsession.ContextWithContent(ctx, vcontent)

    c, err := vcore.Dial(ctx, h.v, dest)
```
https://github.com/v2fly/v2ray-core/blob/efb963237ca5517d8224733041dabeded6f9b104/context.go#L14-L29

**Comment by yuhan6665** [comment]
I wasn't see this issue. What's your json config?

**Comment by rurirei** [comment]
@yuhan6665 
```jsonc
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [  // unused inbound
    {
      "listen": "127.0.0.1",
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          ...
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none"
      },
      "tag": "proxy"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": []
  },
  "stats": {}
}
```

**Comment by yuhan6665** [comment]
@rurirei I tried config similar to yours but can not reproduce the issue. It is quite weird. Do you also have this issue if you turn fake dns on?

```
"fakedns": {
    "ipPool": "240.0.0.0/8",
    "poolSize": 65535
}
"dns": {
        "servers": [
            "fakedns"
            "8.8.8.8",
            "https://1.1.1.1/dns-query"
        ]
},
...
"sniffing": {
        "enabled": true,
        "destOverride": [
            "http",
            "tls",
            "fakedns"
        ]
},
```

**Comment by rurirei** [comment]
> @rurirei I tried config similar to yours but can not reproduce the issue. It is quite weird. Do you also have this issue if you turn fake dns on?
> 
> ```
> "fakedns": {
>     "ipPool": "240.0.0.0/8",
>     "poolSize": 65535
> }
> "dns": {
>         "servers": [
>             "fakedns"
>             "8.8.8.8",
>             "https://1.1.1.1/dns-query"
>         ]
> },
> ...
> "sniffing": {
>         "enabled": true,
>         "destOverride": [
>             "http",
>             "tls",
>             "fakedns"
>         ]
> },
> ```

i'll try it.

**Comment by rurirei** [comment]
@yuhan6665 errors met as well.

**Comment by rurirei** [comment]
especially do not met this if disabled `sniffing`.
```golang
vsniffing := &vproxyman.SniffingConfig{
        Enabled:             false,
        DestinationOverride: []string{"http", "tls", "fakedns"},
        MetadataOnly:        false,
}
```

**Comment by yuhan6665** [comment]
@rurirei based on your error log, the context has some issue when init sniffer. That's why if you turn off sniffer it will be ok.
I think it is issue in your way of init the context.
```
    ctx := vsession.ContextWithID(context.Background(), vsession.NewID())
    ctx = vsession.ContextWithInbound(ctx, vinbound)
    ctx = vsession.ContextWithContent(ctx, vcontent)
```
https://github.com/2dust/AndroidLibV2rayLite

**Comment by rurirei** [comment]
@yuhan6665 that's it. i'll try v.RequireFeatures() to do not uses ctx.
https://github.com/v2fly/v2ray-core/blob/38da831b7550e88bb4e5044ca9856d22a556ac94/app/dispatcher/fakednssniffer.go#L16-L20

**Comment by rurirei** [comment]
seems gently fixed by. https://github.com/v2fly/v2ray-core/blob/38da831b7550e88bb4e5044ca9856d22a556ac94/functions.go#L19

**Comment by rurirei** [comment]
seems ok.
```golang
[v2ray] [Debug] v2ray.com/core/app/dns: domain github.com will use DNS in order: [FakeDNS]
[v2ray] [Info] [3492521930] v2ray.com/core/app/dispatcher: fake dns got domain: github.com for ip: 198.18.0.2
[v2ray] [Info] [3492521930] v2ray.com/core/app/dispatcher: sniffed domain: github.com
[v2ray] [Info] [3492521930] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:github.com:443]
```

**Comment by simo8102** [comment]
Add to config

"sniffing": {
        "enabled": true,
        "destOverride": [
            "http",
            "tls",
            "fakedns"
        ]
},
