### ISSUE TITLE
Windows 4.38.0 V2Ray Core Random Crash

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/v2ray-core#931]
## 你正在使用哪个版本的 V2Ray？

v4.38.0

## 你的使用场景是什么？

使用 qv2ray 客户端添加普通 vmess 节点配置并建立连接，内核来自上游官方发布的 v4.38.0 打包。
当客户端使用 v4.37.3 时，能够正常建立连接并使用。复现问题时只更新了内核，就一定能重现问题。

## 你看到的异常现象是什么？

内核异常退出。

## 你期待看到的正常表现是怎样的？

内核正常工作。不 panic

## 请附上你的配置

**客户端配置：**

<details>

```json
{
    "dns": {
        "servers": [
        ]
    },
    "fakedns": {
        "ipPool": "198.18.0.0/15",
        "poolSize": 65535
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 25556,
            "protocol": "http",
            "settings": {
                "allowTransparent": true,
                "timeout": 300
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls",
                    "fakedns"
                ],
                "enabled": true,
                "metadataOnly": false
            },
            "tag": "http_IN"
        },
        {
            "listen": "0.0.0.0",
            "port": 25555,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true
            },
            "sniffing": {
                "destOverride": [
                    "tls",
                    "http",
                    "fakedns"
                ],
                "enabled": true,
                "metadataOnly": false
            },
            "tag": "socks_IN"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "_QV2RAY_USE_GLOBAL_FORWARD_PROXY_": false,
            "protocol": "vmess",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "{relayserver.domain.tld}",
                        "port": 666666,
                        "users": [
                            {
                                "id": "********-****-****-****-************"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "{proxyserver.domain.tld}"
                },
                "wsSettings": {
                    "headers": {
                        "Host": "{proxyserver.domain.tld}"
                    },
                    "path": "/balabala/balabala/balabala/balabala/balabala/balabala/balabala/balabala"
                },
                "xtlsSettings": {
                    "serverName": "{proxyserver.domain.tld}"
                }
            },
            "tag": "PROXY"
        },
        {
            "protocol": "freedom",
            "sendThrough": "0.0.0.0",
            "settings": {
                "domainStrategy": "AsIs",
                "redirect": ":0"
            },
            "streamSettings": {
            },
            "tag": "DIRECT"
        },
        {
            "protocol": "blackhole",
            "sendThrough": "0.0.0.0",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "streamSettings": {
            },
            "tag": "BLACKHOLE"
        }
    ],
    "routing": {
        "domainMatcher": "",
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "outboundTag": "DIRECT",
                "protocol": [
                    "bittorrent"
                ],
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "BLACKHOLE",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:telegram"
                ],
                "outboundTag": "PROXY",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:category-anticensorship",
                    "geosite:category-dev",
                    "geosite:category-entertainment",
                    "geosite:category-forums",
                    "geosite:category-media",
                    "geosite:category-orgs",
                    "geosite:category-porn",
                    "geosite:category-vpnservices",
                    "geosite:discord",
                    "geosite:google",
                    "geosite:signal",
                    "geosite:speedtest",
                    "geosite:telegram",
                    "geosite:twitter"
                ],
                "outboundTag": "PROXY",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private",
                    "geoip:cn",
                    "162.105.0.0/16",
                    "202.112.7.0/24",
                    "202.112.8.0/24",
                    "222.29.0.0/17",
                    "222.29.128.0/19",
                    "115.27.0.0/16",
                    "2001:da8:201::/48"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            }
        ]
    }
}

```

</details>

## 请附上出错时软件输出的错误日志

**客户端错误日志：**

```
V2Ray 4.38.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 windows/amd64)
A unified platform for anti-censorship.
2021/04/24 21:42:40 [Info] main/jsonem: Reading config: .\config.json
2021/04/24 21:42:43 [Warning] V2Ray 4.38.0 started
panic: Calling IP() on a DomainAddress.

goroutine 21 [running]:
github.com/v2fly/v2ray-core/v4/common/net.domainAddress.IP(...)
        github.com/v2fly/v2ray-core/v4/common/net/address.go:164
github.com/v2fly/v2ray-core/v4/app/dns/fakedns.(*Holder).IsIPInIPPool(0xc0005152c0, 0xda6360, 0xc00206e040, 0x25dda0a87d0)
        github.com/v2fly/v2ray-core/v4/app/dns/fakedns/fake.go:27 +0x38
github.com/v2fly/v2ray-core/v4/app/dispatcher.newFakeDNSSniffer.func2(0xda5100, 0xc001c2aae0, 0xc00065b000, 0xd2, 0x800, 0xc00040c0a8, 0xda5100, 0xc001c2aae0, 0xc00040c0a0)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/fakednssniffer.go:42 +0x20a
github.com/v2fly/v2ray-core/v4/app/dispatcher.newFakeDNSThenOthers.func1(0xda5100, 0xc001c2aae0, 0xc00065b000, 0xd2, 0x800, 0xc00065b000, 0x800, 0x800, 0xd2)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/fakednssniffer.go:96 +0x102
github.com/v2fly/v2ray-core/v4/app/dispatcher.(*Sniffer).Sniff(0xc002e93908, 0xda5100, 0xc001c2a900, 0xc00065b000, 0xd2, 0x800, 0x4, 0x5, 0xc004a50600, 0xc00206e120)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/sniffer.go:61 +0x182
github.com/v2fly/v2ray-core/v4/app/dispatcher.sniffer.func1(0xda5100, 0xc001c2a900, 0xc001c2a990, 0xc000765ea8, 0xc002e93908, 0xd91bc0, 0xc00006e2a0, 0x25dd9fa92b0, 0x18)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:279 +0x167
github.com/v2fly/v2ray-core/v4/app/dispatcher.sniffer(0xda5100, 0xc001c2a900, 0xc001c2a990, 0xc001e46000, 0x0, 0x0, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:289 +0x1cd
github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch.func1(0xc001160260, 0xda5100, 0xc001c2a900, 0xc004a51600, 0x3, 0x4, 0x2030001, 0xc004a500c0, 0xc002e93830, 0xc001c2a8d0, ...)
        github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:237 +0xc5
created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
        github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:232 +0x675

```

**Comment by AkinoKaede** [comment]
I think it might be fixed in 8ba4ac15acb9f6326e94ebcb57ab2d120099b969

**Comment by Loyalsoldier** [comment]
Fixed in 8ba4ac1
