### ISSUE TITLE
panic when loading non-exist geo file tag with the new geo file decoder

### ISSUE THREAD

**Issue by dyhkwong** [v2fly/v2ray-core#952]
## What version of V2Ray are you using?

7e87670 or later

## What problems have you encountered?

panic when loading non-exist geo file tag with the new geo file decoder

## What's your expectation?

expected behavior on versions before 7e87670

```javascript
main: failed to read config files: [**Hide**\config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:nonexist > infra/conf: failed to load geosite: nonexist > infra/conf: list not found in geosite.dat: nonexist
```

## Please attach your configuration here

```javascript
{
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1080,
            "protocol": "socks",
            "settings": {}
        }
    ],
    "log": {
        "loglevel": "debug"
    },
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "rules": [
            {
                "domain": [
                    "geosite:nonexist"
                ],
                "outboundTag": "direct",
                "type": "field"
            }
        ]
    }
}

```

## Please attach error logs here

```javascript
[Warning] common/geodata: failed to decode geodata file: **Hide**\geosite.dat. Fallback to the original ReadFile method.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x1755314]

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common/geodata.LoadSite(0x19a4c8c, 0xb, 0xc0004eb998, 0x8, 0x0, 0x0, 0xc0004f49f0, 0x1, 0x1)
        github.com/v2fly/v2ray-core/v4/common/geodata/load.go:27 +0x1f4
github.com/v2fly/v2ray-core/v4/infra/conf.loadGeositeWithAttr(0x19a4c8c, 0xb, 0xc0004eb998, 0x8, 0xc0003c20b0, 0xc0004df798, 0x10196f4, 0xc000290a50, 0xc0004df7b0)
        github.com/v2fly/v2ray-core/v4/infra/conf/geodata.go:31 +0x330
github.com/v2fly/v2ray-core/v4/infra/conf.loadGeosite(...)
        github.com/v2fly/v2ray-core/v4/infra/conf/geodata.go:16
github.com/v2fly/v2ray-core/v4/infra/conf.parseDomainRule(0xc0004eb990, 0x10, 0xb0, 0x17e5040, 0xc0000fa640, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/infra/conf/router.go:225 +0x1e5
github.com/v2fly/v2ray-core/v4/infra/conf.parseFieldRule(0xc0003c20b0, 0xae, 0xb0, 0x1, 0xc000096d01, 0x0)
        github.com/v2fly/v2ray-core/v4/infra/conf/router.go:441 +0xc05
github.com/v2fly/v2ray-core/v4/infra/conf.ParseRule(0xc0003c20b0, 0xae, 0xb0, 0xc0004dfa20, 0xecf125, 0xc0000ba980)
        github.com/v2fly/v2ray-core/v4/infra/conf/router.go:519 +0x1f2
github.com/v2fly/v2ray-core/v4/infra/conf.(*RouterConfig).Build(0xc0000d21e0, 0xc0000ba988, 0x3, 0xc00009d5d8)
        github.com/v2fly/v2ray-core/v4/infra/conf/router.go:98 +0x191
github.com/v2fly/v2ray-core/v4/infra/conf.(*Config).Build(0xc0003c4000, 0xc0000d0990, 0xc0003c40e0, 0x0)
        github.com/v2fly/v2ray-core/v4/infra/conf/v2ray.go:536 +0x1e11
github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1(0x182c760, 0xc00009c1e0, 0xc0000872e3, 0x4, 0xc00003bc30)
        github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:36 +0xaf
github.com/v2fly/v2ray-core/v4.LoadConfig(0x199e988, 0x4, 0xc0000872c0, 0x27, 0x182c760, 0xc00009c1e0, 0x1ad7580, 0xc000006018, 0xc0004dfe88)
        github.com/v2fly/v2ray-core/v4/config.go:67 +0x26c
main.startV2Ray(0xc000060120, 0xc0000541f0, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/main/main.go:110 +0x135
main.main()
        github.com/v2fly/v2ray-core/v4/main/main.go:139 +0xbf
```

**Comment by Loyalsoldier** [comment]
Fixed by #953
